import axios from "axios";
import Head from "next/head";
import md5 from "md5";

import { useEffect, useState } from "react";
import MarvelComics from "../Components/MarvelComics";
import MarvelCharacters from "../Components/MarvelCharacters";
import MarvelStories from "../Components/MarvelStories";

export default function Home() {
  const [dataState, setDataState] = useState([]);
  const [characterData, setCharacterData] = useState([]);
  const [storiesData, setStoriesData] = useState([]);
  const baseURL = "http://gateway.marvel.com/v1/public/";
  const publicKey = "7dde07668a32d9f40655df6fc7622531";
  const privateKey = "797819fdd8761cfa29f64fa4e365f1a3db7bd0c4";

  const time = Number(new Date());

  const hash = md5(time + privateKey + publicKey);
  useEffect(() => {
    axios
      .get(
        `http://gateway.marvel.com/v1/public/comics?ts=${time}&apikey=${publicKey}&hash=${hash}`
      )
      .then((res) => setDataState(res.data.data.results))
      .catch((err) => console.log(err));
    axios
      .get(
        `http://gateway.marvel.com/v1/public/characters?ts=${time}&apikey=${publicKey}&hash=${hash}`
      )
      .then((res) => setCharacterData(res.data.data.results));
    axios
      .get(
        `http://gateway.marvel.com/v1/public/stories?ts=${time}&apikey=${publicKey}&hash=${hash}`
      )
      .then((res) => setStoriesData(res.data.data.results));
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="flex w-full justify-center items-center">
          <img
            height="100"
            width="300"
            src="https://logos-world.net/wp-content/uploads/2020/11/Marvel-Studios-Symbol.png"
            alt=""
          />
        </div>
        <div className="flex flex-col space-y-28 overflow-hidden">
          <MarvelComics dataState={dataState} setDataState={setDataState} />
          <MarvelCharacters
            dataState={characterData}
            setDataState={setCharacterData}
          />
          <MarvelStories
            dataState={storiesData}
            setDataState={setStoriesData}
          />
        </div>
      </div>
    </div>
  );
}
